# Generated by Django 3.0.3 on 2020-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('license_plate_number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=50)),
                ('car_brand', models.SmallIntegerField(choices=[(1, 'BMW'), (2, 'Audi'), (3, 'Mercedes-benz'), (4, 'Wolksvagen'), (5, 'Choose a car brand')])),
            ],
        ),
    ]
