# Generated by Django 3.0.3 on 2020-02-19 08:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_ukraine', '0003_auto_20200219_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('order_address', models.CharField(max_length=120)),
                ('distination_address', models.CharField(max_length=120)),
                ('desired_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Cancel'), (1, 'New'), (2, 'In-processing'), (4, 'Completed')])),
                ('taxi_driver', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name': 'Dispatch', 'verbose_name_plural': 'Dispatches'},
        ),
    ]
