# Generated by Django 3.0.3 on 2020-02-19 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi_ukraine', '0004_auto_20200219_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
